server:
  port: 8081

spring:

  datasource:   # mysql连接信息
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 314618

  data:        # redis连接信息
    redis:
      host: 192.168.88.128
      port: 6380
      database: 0
      client-type: lettuce
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s


  jackson:
    default-property-inclusion: non_null # JSON?????????
  ai:
    vectorstore:    # 矢量数据库
      redis:
        initialize-schema: true
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      model: "deepseek-chat"
      #sk-6d42913bd47d45999a1811ba7b815f7e
#      chat:
#        enabled: false   # 关闭自动配置
    ollama:      # 使用本地ollama的嵌入模型
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text

    model:
      chat: deepseek
      embedding:
        text: ollama




mybatis-plus:
  type-aliases-package: com.xjtu.entity # 扫描包
  configuration:
    map-underscore-to-camel-case: true   # 驼峰命名转换
    cache-enabled: false    # ????????
  global-config:
    db-config:
      id-type: assign_id #雪花算法
      update-strategy: not_null  # ????????????
